package com.shanemulcair.projecteuler;

import java.util.ArrayList;
import java.util.List;

/*
 * Each new term in the Fibonacci sequence is generated by
 * adding the previous two terms. By starting with 1 and 2,
 * the first 10 terms will be:
 *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values
 * do not exceed four million, find the sum of the even-valued terms.
 * 
 */
public class Problem2 {

	public int getSumOfFibonacci(int ceiling){
		int sum=0;
		List<Integer> fibs=new ArrayList<Integer>();
		fibs=getFibs(ceiling);
		for(int i:fibs){
			if(i%2==0){
				sum+=i;
			}
		}
		return sum;
	}
	
	private List<Integer> getFibs(int ceiling){
		List<Integer> fibs=new ArrayList<Integer>();
		int sum=1;
		int first=0;
		int second=1;
		while(sum<ceiling){
			sum=fibGen(first,second);
			first=second;
			second=sum;
			if(sum<ceiling){
			fibs.add(sum);
			}
		}
		return fibs;
	}
	
	private int fibGen(int a, int b){
		return a+b;
	}
	
	
}
